jobs:
  ci:
    name: ci
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: set up JDK ${{matrix.version}} (${{matrix.dist}})
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.dist }}
        java-version: ${{ matrix.version }}
    - continue-on-error: true
      name: test
      run: ./gradlew --info test --no-daemon
    strategy:
      matrix:
        dist:
        - microsoft
        version:
        - 11.0.13
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
