jobs:
  greeting:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/first-interaction@v1
      with:
        issue-message: This is your first issue in the repository. Thank you for raising
          this issue.' first issue
        pr-message: This is your first pull request in the repository. Thank you for
          this patch. Please review the Wiki page in the repository before submitting
          a PR.' first pr
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Greetings
on:
  repository_dispatch:
    types: trigger-ga___greetings.yml
