jobs:
  triage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/labeler@v3-preview
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Pull Request Labeler
on:
  repository_dispatch:
    types: trigger-ga___label.yml
