jobs:
  gradle-java8:
    name: Java 8 release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: microsoft
        java-version: 11
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew clean build javadoc --stacktrace --warning-mode all --no-daemon
    - continue-on-error: true
      id: branch_tag
      name: Branch tag
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - continue-on-error: true
      env:
        JFROG_KEY: ${{ secrets.JFROG_KEY }}
        JFROG_USER: ${{ secrets.JFROG_USER }}
        RELEASE_TAG: ${{ steps.branch_tag.outputs.RELEASE_TAG }}
      name: Publish to Jfrog
      run: ./scripts/publishToJfrog.sh
name: tag (release) flow
on:
  repository_dispatch:
    types: trigger-ga___tag.yml
